/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cities: City;
    organisers: Organiser;
    venues: Venue;
    seasons: Season;
    events: Event;
    'event-reviews': EventReview;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    seasons: {
      events: 'events';
    };
    events: {
      reviews: 'event-reviews';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    organisers: OrganisersSelect<false> | OrganisersSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-reviews': EventReviewsSelect<false> | EventReviewsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'review-settings': ReviewSetting;
  };
  globalsSelect: {
    'review-settings': ReviewSettingsSelect<false> | ReviewSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Legacy accounts without a role retain administrator access. New accounts default to reviewer.
   */
  role?: ('admin' | 'reviewer' | 'approver') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Add cities and update their names, countries and local time zones. The seeded cities are starter data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  slug: string;
  country: string;
  timezone: string;
  timezoneLabel: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisers".
 */
export interface Organiser {
  id: number;
  name: string;
  slug: string;
  type: 'brand' | 'label' | 'gallery' | 'promoter' | 'institution' | 'individual';
  website?: string | null;
  /**
   * Internal only. Never included in public event responses.
   */
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  name: string;
  slug: string;
  city: number | City;
  area?: string | null;
  address?: string | null;
  mapUrl?: string | null;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  name: string;
  slug: string;
  city: number | City;
  startDate?: string | null;
  endDate?: string | null;
  description?: string | null;
  status: 'provisional' | 'final';
  /**
   * Internal aliases; never use as product labels.
   */
  searchAliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  isPublished?: boolean | null;
  isDemo?: boolean | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * All entries start Submitted. Complete review, approve, then publish in separate saves. Content changes require reapproval.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  city: number | City;
  /**
   * Enter with a timezone offset. Stored as UTC.
   */
  startAt: string;
  endAt?: string | null;
  allDay?: boolean | null;
  industry:
    | 'fashion'
    | 'art'
    | 'music'
    | 'design'
    | 'film-television'
    | 'technology'
    | 'business'
    | 'food-drink'
    | 'beauty'
    | 'sport';
  secondaryIndustry?:
    | (
        | 'fashion'
        | 'art'
        | 'music'
        | 'design'
        | 'film-television'
        | 'technology'
        | 'business'
        | 'food-drink'
        | 'beauty'
        | 'sport'
      )
    | null;
  eventType:
    | 'show'
    | 'presentation'
    | 'exhibition'
    | 'opening'
    | 'concert'
    | 'performance'
    | 'screening'
    | 'talk'
    | 'conference'
    | 'dinner'
    | 'party'
    | 'launch'
    | 'pop-up'
    | 'run';
  access: 'tickets' | 'free' | 'rsvp' | 'invitation-only' | 'private';
  visibility: 'public' | 'industry' | 'held-date';
  actionUrl?: string | null;
  organiser: number | Organiser;
  venue?: (number | null) | Venue;
  seasons?: (number | Season)[] | null;
  description?: string | null;
  status: 'submitted' | 'approved' | 'published' | 'cancelled' | 'postponed';
  /**
   * Mark only after direct organiser confirmation. Demo data is never verified.
   */
  verified?: boolean | null;
  organiserConfirmed?: boolean | null;
  organiserConfirmedBy?: (number | null) | User;
  organiserConfirmedAt?: string | null;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  publishedAt?: string | null;
  source: 'fola' | 'submission' | 'csv' | 'demo';
  sourceUrl?: string | null;
  /**
   * Private contact details. Never exposed on the public calendar.
   */
  submittedBy?: {
    name?: string | null;
    email?: string | null;
    relationship?: ('organiser' | 'pr' | 'venue' | 'other') | null;
  };
  isDemo?: boolean | null;
  reviews?: {
    docs?: (number | EventReview)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * AI findings and the original listing are retained alongside the human decision. Pending AI reviews need the review worker integration.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-reviews".
 */
export interface EventReview {
  id: number;
  event: number | Event;
  originalListing:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aiStatus: 'pending' | 'processing' | 'completed' | 'failed';
  promptVersion?: string | null;
  promptSnapshot?: string | null;
  model?: string | null;
  findings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  summary?: string | null;
  suggestedListing?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recommendation?: ('approve-as-submitted' | 'approve-with-edits' | 'request-information' | 'reject') | null;
  draftMessage?: string | null;
  failureReason?: string | null;
  humanDecision: 'pending' | 'accepted' | 'amended' | 'request-information' | 'rejected';
  decisionNotes?: string | null;
  decidedBy?: (number | null) | User;
  decidedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'organisers';
        value: number | Organiser;
      } | null)
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-reviews';
        value: number | EventReview;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  timezone?: T;
  timezoneLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisers_select".
 */
export interface OrganisersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  website?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  area?: T;
  address?: T;
  mapUrl?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  status?: T;
  searchAliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  isPublished?: T;
  isDemo?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  city?: T;
  startAt?: T;
  endAt?: T;
  allDay?: T;
  industry?: T;
  secondaryIndustry?: T;
  eventType?: T;
  access?: T;
  visibility?: T;
  actionUrl?: T;
  organiser?: T;
  venue?: T;
  seasons?: T;
  description?: T;
  status?: T;
  verified?: T;
  organiserConfirmed?: T;
  organiserConfirmedBy?: T;
  organiserConfirmedAt?: T;
  approvedBy?: T;
  approvedAt?: T;
  publishedAt?: T;
  source?: T;
  sourceUrl?: T;
  submittedBy?:
    | T
    | {
        name?: T;
        email?: T;
        relationship?: T;
      };
  isDemo?: T;
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-reviews_select".
 */
export interface EventReviewsSelect<T extends boolean = true> {
  event?: T;
  originalListing?: T;
  aiStatus?: T;
  promptVersion?: T;
  promptSnapshot?: T;
  model?: T;
  findings?: T;
  summary?: T;
  suggestedListing?: T;
  recommendation?: T;
  draftMessage?: T;
  failureReason?: T;
  humanDecision?: T;
  decisionNotes?: T;
  decidedBy?: T;
  decidedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Prompt configuration for the future Anthropic review worker. No credentials are stored in this document.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-settings".
 */
export interface ReviewSetting {
  id: number;
  promptVersion: string;
  systemPrompt: string;
  /**
   * Set a supported Anthropic model when enabling the review worker.
   */
  model?: string | null;
  turnaroundWorkingDays: number;
  minimumVerifiedEventsPerCity: number;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-settings_select".
 */
export interface ReviewSettingsSelect<T extends boolean = true> {
  promptVersion?: T;
  systemPrompt?: T;
  model?: T;
  turnaroundWorkingDays?: T;
  minimumVerifiedEventsPerCity?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}