/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    cities: City;
    organisers: Organiser;
    venues: Venue;
    seasons: Season;
    events: Event;
    'event-reviews': EventReview;
    'email-notifications': EmailNotification;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    seasons: {
      events: 'events';
    };
    events: {
      reviews: 'event-reviews';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    organisers: OrganisersSelect<false> | OrganisersSelect<true>;
    venues: VenuesSelect<false> | VenuesSelect<true>;
    seasons: SeasonsSelect<false> | SeasonsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    'event-reviews': EventReviewsSelect<false> | EventReviewsSelect<true>;
    'email-notifications': EmailNotificationsSelect<false> | EmailNotificationsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'review-settings': ReviewSetting;
  };
  globalsSelect: {
    'review-settings': ReviewSettingsSelect<false> | ReviewSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      'review-event': TaskReviewEvent;
      'send-event-email': TaskSendEventEmail;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Legacy accounts without a role retain administrator access. New accounts default to reviewer.
   */
  role?: ('admin' | 'reviewer' | 'approver') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Add cities and update their names, countries and local time zones. The seeded cities are starter data.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * Automatically filled from name. You can edit it manually or use Generate slug to regenerate it.
   */
  slug: string;
  country: string;
  /**
   * Suggested from matching city names. Enter or correct the IANA timezone when needed.
   */
  timezone: string;
  /**
   * Automatically suggested from the timezone; you can edit it.
   */
  timezoneLabel: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisers".
 */
export interface Organiser {
  id: number;
  name: string;
  /**
   * Automatically filled from name. You can edit it manually or use Generate slug to regenerate it.
   */
  slug: string;
  type: 'brand' | 'label' | 'gallery' | 'promoter' | 'institution' | 'individual';
  website?: string | null;
  /**
   * Internal only. Never included in public event responses.
   */
  contact?: {
    name?: string | null;
    email?: string | null;
    phone?: string | null;
  };
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues".
 */
export interface Venue {
  id: number;
  name: string;
  /**
   * Automatically filled from name. You can edit it manually or use Generate slug to regenerate it.
   */
  slug: string;
  city: number | City;
  area?: string | null;
  address?: string | null;
  mapUrl?: string | null;
  isDemo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons".
 */
export interface Season {
  id: number;
  name: string;
  /**
   * Automatically filled from name. You can edit it manually or use Generate slug to regenerate it.
   */
  slug: string;
  city: number | City;
  startDate?: string | null;
  endDate?: string | null;
  description?: string | null;
  status: 'provisional' | 'final';
  /**
   * Internal aliases; never use as product labels.
   */
  searchAliases?:
    | {
        alias: string;
        id?: string | null;
      }[]
    | null;
  isPublished?: boolean | null;
  isDemo?: boolean | null;
  events?: {
    docs?: (number | Event)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Public submissions require AI review and administrator approval. Choose existing organiser/venue records or create them from the submitted details on approval. Publishing records approval too. Content changes require reapproval.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  /**
   * Automatically filled from title. You can edit it manually or use Generate slug to regenerate it.
   */
  slug: string;
  city: number | City;
  startAt: string;
  endAt?: string | null;
  allDay?: boolean | null;
  industry:
    | 'fashion'
    | 'art'
    | 'music'
    | 'design'
    | 'film-television'
    | 'technology'
    | 'business'
    | 'food-drink'
    | 'beauty'
    | 'sport';
  secondaryIndustry?:
    | (
        | 'fashion'
        | 'art'
        | 'music'
        | 'design'
        | 'film-television'
        | 'technology'
        | 'business'
        | 'food-drink'
        | 'beauty'
        | 'sport'
      )
    | null;
  eventType:
    | 'show'
    | 'presentation'
    | 'exhibition'
    | 'opening'
    | 'concert'
    | 'performance'
    | 'screening'
    | 'talk'
    | 'conference'
    | 'dinner'
    | 'party'
    | 'launch'
    | 'pop-up'
    | 'run';
  access: 'tickets' | 'free' | 'rsvp' | 'invitation-only' | 'private';
  visibility: 'public' | 'industry' | 'held-date';
  actionUrl?: string | null;
  /**
   * Choose an existing organiser after reviewing possible AI matches. Required before approval for manually entered events.
   */
  organiser?: (number | null) | Organiser;
  venue?: (number | null) | Venue;
  /**
   * Private submitted details. No organiser record is created until administrator approval. Editing these details requires a new AI review.
   */
  submittedOrganiser?: {
    name?: string | null;
    type?: ('brand' | 'label' | 'gallery' | 'promoter' | 'institution' | 'individual') | null;
    website?: string | null;
    contactEmail?: string | null;
  };
  organiserResolution?: ('use-existing' | 'update-existing' | 'create-new') | null;
  organiserUpdate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Private submitted details. Match a venue in this city or create it on approval. Editing these details requires a new AI review.
   */
  submittedVenue?: {
    name?: string | null;
    area?: string | null;
    address?: string | null;
    mapUrl?: string | null;
  };
  venueResolution?: ('use-existing' | 'update-existing' | 'create-new' | 'omit') | null;
  venueUpdate?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  seasons?: (number | Season)[] | null;
  description?: string | null;
  status: 'submitted' | 'approved' | 'published' | 'cancelled' | 'postponed';
  /**
   * Mark only after direct organiser confirmation. Demo data is never verified.
   */
  verified?: boolean | null;
  organiserConfirmed?: boolean | null;
  organiserConfirmedBy?: (number | null) | User;
  organiserConfirmedAt?: string | null;
  approvedBy?: (number | null) | User;
  approvedAt?: string | null;
  publishedAt?: string | null;
  source: 'fola' | 'submission' | 'csv' | 'demo';
  sourceUrl?: string | null;
  /**
   * Private contact details. Never exposed on the public calendar.
   */
  submittedBy?: {
    name?: string | null;
    email?: string | null;
    relationship?: ('organiser' | 'pr' | 'venue' | 'other') | null;
  };
  isDemo?: boolean | null;
  reviews?: {
    docs?: (number | EventReview)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * AI findings and submitted details are retained alongside the human decision. Public submissions require completed AI review; administrator approval or publication records the final decision.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-reviews".
 */
export interface EventReview {
  id: number;
  event: number | Event;
  originalListing:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Anthropic processes queued reviews. To retry a failed review, set this to Pending. Public submissions cannot be approved until AI review completes.
   */
  aiStatus: 'pending' | 'processing' | 'completed' | 'failed';
  promptVersion?: string | null;
  promptSnapshot?: string | null;
  model?: string | null;
  findings?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  summary?: string | null;
  suggestedListing?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  recommendation?: ('approve-as-submitted' | 'approve-with-edits' | 'request-information' | 'reject') | null;
  draftMessage?: string | null;
  failureReason?: string | null;
  humanDecision: 'pending' | 'accepted' | 'amended' | 'request-information' | 'rejected';
  /**
   * Optional notes explaining the human decision.
   */
  decisionNotes?: string | null;
  decidedBy?: (number | null) | User;
  decidedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Private delivery records for publication emails and historical submission receipts. Failed jobs can be retried from Jobs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-notifications".
 */
export interface EmailNotification {
  id: number;
  key: string;
  eventId: number;
  kind: 'submitted' | 'published';
  status: 'queued' | 'sent' | 'skipped' | 'failed';
  message?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  firstAttemptAt?: string | null;
  sentAt?: string | null;
  providerId?: string | null;
  failureReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'review-event' | 'send-event-email';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'review-event' | 'send-event-email') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  /**
   * Used for concurrency control. Jobs with the same key are subject to exclusive/supersedes rules.
   */
  concurrencyKey?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'organisers';
        value: number | Organiser;
      } | null)
    | ({
        relationTo: 'venues';
        value: number | Venue;
      } | null)
    | ({
        relationTo: 'seasons';
        value: number | Season;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'event-reviews';
        value: number | EventReview;
      } | null)
    | ({
        relationTo: 'email-notifications';
        value: number | EmailNotification;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  country?: T;
  timezone?: T;
  timezoneLabel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "organisers_select".
 */
export interface OrganisersSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  type?: T;
  website?: T;
  contact?:
    | T
    | {
        name?: T;
        email?: T;
        phone?: T;
      };
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "venues_select".
 */
export interface VenuesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  area?: T;
  address?: T;
  mapUrl?: T;
  isDemo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seasons_select".
 */
export interface SeasonsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  city?: T;
  startDate?: T;
  endDate?: T;
  description?: T;
  status?: T;
  searchAliases?:
    | T
    | {
        alias?: T;
        id?: T;
      };
  isPublished?: T;
  isDemo?: T;
  events?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  city?: T;
  startAt?: T;
  endAt?: T;
  allDay?: T;
  industry?: T;
  secondaryIndustry?: T;
  eventType?: T;
  access?: T;
  visibility?: T;
  actionUrl?: T;
  organiser?: T;
  venue?: T;
  submittedOrganiser?:
    | T
    | {
        name?: T;
        type?: T;
        website?: T;
        contactEmail?: T;
      };
  organiserResolution?: T;
  organiserUpdate?: T;
  submittedVenue?:
    | T
    | {
        name?: T;
        area?: T;
        address?: T;
        mapUrl?: T;
      };
  venueResolution?: T;
  venueUpdate?: T;
  seasons?: T;
  description?: T;
  status?: T;
  verified?: T;
  organiserConfirmed?: T;
  organiserConfirmedBy?: T;
  organiserConfirmedAt?: T;
  approvedBy?: T;
  approvedAt?: T;
  publishedAt?: T;
  source?: T;
  sourceUrl?: T;
  submittedBy?:
    | T
    | {
        name?: T;
        email?: T;
        relationship?: T;
      };
  isDemo?: T;
  reviews?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event-reviews_select".
 */
export interface EventReviewsSelect<T extends boolean = true> {
  event?: T;
  originalListing?: T;
  aiStatus?: T;
  promptVersion?: T;
  promptSnapshot?: T;
  model?: T;
  findings?: T;
  summary?: T;
  suggestedListing?: T;
  recommendation?: T;
  draftMessage?: T;
  failureReason?: T;
  humanDecision?: T;
  decisionNotes?: T;
  decidedBy?: T;
  decidedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "email-notifications_select".
 */
export interface EmailNotificationsSelect<T extends boolean = true> {
  key?: T;
  eventId?: T;
  kind?: T;
  status?: T;
  message?: T;
  firstAttemptAt?: T;
  sentAt?: T;
  providerId?: T;
  failureReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  concurrencyKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Anthropic reviews submitted events and suggests edits. Staff make publication decisions. API credentials stay in server environment variables.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-settings".
 */
export interface ReviewSetting {
  id: number;
  promptVersion: string;
  systemPrompt: string;
  /**
   * Claude on Anthropic with strict structured output. Set ANTHROPIC_MODEL in the server environment to override the default model.
   */
  model?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "review-settings_select".
 */
export interface ReviewSettingsSelect<T extends boolean = true> {
  promptVersion?: T;
  systemPrompt?: T;
  model?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskReview-event".
 */
export interface TaskReviewEvent {
  input: {
    reviewId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSend-event-email".
 */
export interface TaskSendEventEmail {
  input: {
    notificationId: number;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}